# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
name: myBuil
on:
    pull_request:
        branches: [master, main]
jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --production=false
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          host: ${{ secrets.SONAR_HOST_URL }} # Variable set in the Github Secrets
          token: ${{ secrets.SONAR_TOKEN }} # Variable set in the Github Secrets
